### ISSUE TITLE
Open source checklist

### ISSUE THREAD

**Issue by nkshah2** [nkshah2/flutter_awesome_button#9]
- [x] License file
- [x] Readme
- [x] Contribution guide
- [x] Issue template
- [x] PR template
- [x] Code of conduct
- [x] CICD if needed
- [x] Automated PR review tasks if needed
